'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AffiliateProgramNew
    Public Property AffiliateProgramId As Integer
    Public Property UserId As Integer
    Public Property Name As String
    Public Property Description As String
    Public Property PayPerLead As Integer
    Public Property PayPerSale As Integer
    Public Property CookieDays As Integer
    Public Property InfoUrl As String
    Public Property WebUrl As String
    Public Property PctFlag As Nullable(Of Integer)
    Public Property Amt1 As Nullable(Of Integer)
    Public Property Amt2 As Nullable(Of Integer)
    Public Property Offline As Nullable(Of Integer)
    Public Property EmailNotice As String
    Public Property EmailOrders As String
    Public Property MailListId As Nullable(Of Integer)

End Class
