'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class AffiliateList
        Public Property UserId As Integer
        Public Property AffiliateListid As Integer
        Public Property AffiliateName As String
        Public Property AffiliateProgramId As Integer
        Public Property AffiliateLevel As Integer
        Public Property Email As String
        Public Property TaxId As String
        Public Property WebSite As String
        Public Property Status As Integer
        Public Property Password As String
        Public Property ProtectiveId As String
        Public Property W9 As Nullable(Of Boolean)
        Public Property Fax As String
        Public Property Address As String
        Public Property Address2 As String
        Public Property City As String
        Public Property State As String
        Public Property Zip As String
        Public Property Country As String
        Public Property FacebookId As String
        Public Property TwitterId As String
        Public Property Phone As String
    
    End Class

End Namespace
