'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class AffiliateLink
        Public Property AffiliateLinkId As Integer
        Public Property AffiliateProgramId As Integer
        Public Property TypeOfLink As Byte
        Public Property Link As String
        Public Property LinkText As String
        Public Property ImageLink As String
        Public Property Height As Nullable(Of Short)
        Public Property Width As Nullable(Of Short)
        Public Property EmailLink As String
        Public Property EmailSubjectLine As String
    
        Public Overridable Property AffiliateProgram As AffiliateProgram
    
    End Class

End Namespace
