'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class Affiliate
        Public Property AffiliateId As Integer
        Public Property AffiliateProgramId As Integer
        Public Property ReferredById As Nullable(Of Integer)
        Public Property AffiliateLevel As Short
        Public Property Email As String
        Public Property TaxId As String
        Public Property WebSite As String
        Public Property Status As Short
        Public Property Password As String
        Public Property ProtectiveId As String
        Public Property W9 As Nullable(Of Boolean)
        Public Property Fax As String
        Public Property Name As String
        Public Property Address As String
        Public Property Address2 As String
        Public Property City As String
        Public Property State As String
        Public Property Zip As String
        Public Property Country As String
        Public Property FacebookId As String
        Public Property TwitterId As String
        Public Property Phone As String
    
        Public Overridable Property AffiliateProgram As AffiliateProgram
    
    End Class

End Namespace
