'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CaptureEmail
    Public Property CaptureEmailId As Integer
    Public Property OrderId As Integer
    Public Property EmailAddress As String
    Public Property TimeAdded As Byte()

    Public Overridable Property OrderHeader As OrderHeader

End Class
