'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CatalogImage
    Public Property CatalogImageId As Integer
    Public Property CatalogItemId As Integer
    Public Property Sequence As Short
    Public Property ImageThumb As String
    Public Property ImageLink As String

    Public Overridable Property CatalogItem As CatalogItem

End Class
