'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class Category
        Public Property CategoryId As Integer
        Public Property Name As String
        Public Property Description As String
        Public Property UserId As Integer
        Public Property CreatedOn As Date
        Public Property CreatedBy As Integer
        Public Property ModifiedOn As Date
        Public Property ModifiedBy As Integer
        Public Property Deleted As Boolean
        Public Property DeletedOn As Nullable(Of Date)
        Public Property DeletedBy As Nullable(Of Integer)
        Public Property Sequence As Integer
    
    End Class

End Namespace
