'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class ColorPalette
        Public Property ColorPaletteId As Integer
        Public Property PaletteName As String
        Public Property ColorPaletteColor As String
        Public Property CatalogBackground As String
        Public Property CatalogFont As String
        Public Property CatalogBorder As String
        Public Property CatalogFontName As String
        Public Property CatalogFontSize As Nullable(Of Byte)
        Public Property CatalogHeaderColor As String
        Public Property CatalogHeaderFontColor As String
        Public Property ItemBackground As String
        Public Property ItemNameFontColor As String
        Public Property ItemNameFontSize As String
        Public Property CategoryBackground As String
        Public Property CategoryFont As String
        Public Property CategoryFontSize As Nullable(Of Byte)
        Public Property DepartmentBackground As String
        Public Property DepartmentFont As String
        Public Property DepartmentFontSize As Nullable(Of Byte)
        Public Property OrderSummaryBackground As String
        Public Property OrderSummaryFont As String
        Public Property OrderSummaryFontSize As Nullable(Of Byte)
        Public Property OrderSummaryBorder As String
        Public Property OrderSummaryHeaderBackground As String
        Public Property OrderSummaryHeaderFont As String
        Public Property OrderPopupBackground As String
        Public Property OrderPopupFont As String
        Public Property OrderPopupBorder As String
        Public Property OrderPopupNameColor As String
        Public Property LoginBackground As String
        Public Property LoginFont As String
        Public Property LoginBorder As String
        Public Property LoginFontSize As Nullable(Of Byte)
        Public Property LoginButtonsColor As String
        Public Property LoginButtonsFont As String
        Public Property LoginGuestButtonColor As String
        Public Property LoginGuestFont As String
        Public Property LoginGuestBorder As String
        Public Property PaymentBackground As String
        Public Property PaymentFont As String
        Public Property PaymentBorder As String
        Public Property PaymentFontSize As Nullable(Of Byte)
        Public Property PaymentButtonsColor As String
        Public Property PaymentButtonsFont As String
        Public Property PaymentBackButtonColor As String
        Public Property PaymentBackFont As String
        Public Property PaymentBackBorder As String
    
    End Class

End Namespace
