'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ColorPaletteOld
    Public Property ColorPaletteId As Integer
    Public Property ColorPaletteName As String
    Public Property ColorPaletteColor As String
    Public Property CategoryHover As String
    Public Property CategoryHoverFontColor As String
    Public Property CategoryBackground As String
    Public Property CategoryFontColor As String
    Public Property PopupBackColor As String
    Public Property PopupFontColor As String
    Public Property PaymentBackColor As String
    Public Property PaymentFontColor As String
    Public Property ItemBackColor As String
    Public Property ItemFontColor As String
    Public Property ItemNameColor As String
    Public Property RightSideBackColor As String
    Public Property RightSideFontColor As String
    Public Property LeftSideBackColor As String
    Public Property LeftSideFontColor As String
    Public Property DepartmentBackColor As String
    Public Property DepartmentFontColor As String

End Class
