'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class Country
        Public Property Country1 As String
        Public Property Name As String
        Public Property Code3 As String
        Public Property CurrencyCode As String
        Public Property CurrencyName As String
        Public Property Sequence As Nullable(Of Short)
    
    End Class

End Namespace
