'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CountryCodesComplete
    Public Property CountryCodesId As Integer
    Public Property CountryName As String
    Public Property Code As String
    Public Property Code3 As String
    Public Property CountryNumeric As Short
    Public Property UpsFrom As Nullable(Of Boolean)
    Public Property Fedex As Nullable(Of Boolean)
    Public Property NiftyCart As Nullable(Of Boolean)
    Public Property Usps As Nullable(Of Boolean)
    Public Property UpsTo As Nullable(Of Boolean)
    Public Property UpsStar As String

End Class
