'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class CustomerSelectPlan
        Public Property CustomerSelectPlanId As Integer
        Public Property UserId As Integer
        Public Property PlanName As String
        Public Property MonthyPrice As Nullable(Of Decimal)
        Public Property NiftyBuyButton As Nullable(Of Boolean)
        Public Property NumberOfProducts As String
        Public Property FileStorage As String
        Public Property Support247 As Nullable(Of Boolean)
        Public Property TransactionFees As String
        Public Property WordpressPlugin As Nullable(Of Boolean)
        Public Property EzshipCalculation As Nullable(Of Boolean)
        Public Property WebSiteBlog As Nullable(Of Boolean)
        Public Property GiftCards As Nullable(Of Boolean)
        Public Property LiveChatOnPage As Nullable(Of Boolean)
        Public Property InterfacetoQuickBooks As Nullable(Of Boolean)
        Public Property InterfacetoEmailProviders As Nullable(Of Boolean)
        Public Property CustomerAccounts As Nullable(Of Boolean)
        Public Property PaypalCheckout As Nullable(Of Boolean)
        Public Property ProfessionalReports As Nullable(Of Boolean)
        Public Property AbandonedCartRecovery As Nullable(Of Boolean)
        Public Property SaveOrderForLater As Nullable(Of Boolean)
        Public Property AdvanceReportBuilder As Nullable(Of Boolean)
        Public Property AffiliateProgram As Nullable(Of Boolean)
        Public Property FacebookGoogleTracking As Nullable(Of Boolean)
        Public Property ManyCreditCardOptions As Nullable(Of Boolean)
        Public Property ThirdPartyCalculatedShippingRates As Nullable(Of Boolean)
        Public Property ConciergeSupport As Nullable(Of Boolean)
        Public Property BillingCycle As String
        Public Property Free2Months As Nullable(Of Boolean)
        Public Property Free6Months As Nullable(Of Boolean)
        Public Property Active As Boolean
    
    End Class

End Namespace
