'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EzShip
    Public Property EzShipId As Integer
    Public Property UserId As Integer
    Public Property Country As String
    Public Property Description As String
    Public Property FirstItem As Nullable(Of Decimal)
    Public Property NextItems As Nullable(Of Decimal)
    Public Property FreeOver As Nullable(Of Decimal)
    Public Property CountryRegion As String
    Public Property DefaultMethod As Boolean

    Public Overridable Property OurCustomer As OurCustomer

End Class
