'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class HelpMessage
        Public Property HelpId As Integer
        Public Property ComponentName As String
        Public Property LanguageId As Nullable(Of Integer)
        Public Property Json As String
    
    End Class

End Namespace
