'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class ItemUpsell
        Public Property ItemUpsellId As Integer
        Public Property UserId As Integer
        Public Property Description As String
        Public Property Price As Decimal
        Public Property CatalogItemId As Nullable(Of Integer)
    
        Public Overridable Property OurCustomer As OurCustomer
    
    End Class

End Namespace
