'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ItemSubOption
    Public Property SubOptionId As Integer
    Public Property UserId As Integer
    Public Property Description As String
    Public Property Price As Decimal

    Public Overridable Property OurCustomer As OurCustomer
    Public Overridable Property OrderSubOptions As ICollection(Of OrderSubOption) = New HashSet(Of OrderSubOption)

End Class
