'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ItemUpsellGroup
    Public Property ItemUpsellGroupId As Integer
    Public Property UserId As Integer
    Public Property Name As String
    Public Property Sequence As Byte
    Public Property Description As String
    Public Property CheckBox As Boolean
    Public Property ItemUpsellId As Nullable(Of Integer)
    Public Property UpsellAsGroup As Boolean

End Class
