'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class Language
        Public Property LanguageId As Integer
        Public Property Name As String
        Public Property FirstNameField As String
        Public Property LastNameField As String
        Public Property ZipCodeField As String
        Public Property EmailField As String
        Public Property PhoneField As String
        Public Property CreditCardField As String
        Public Property ExpirationDateField As String
        Public Property CreditCardCodeField As String
        Public Property FinalCheckOutButton As String
        Public Property BackButton As String
        Public Property ShipToHeader As String
        Public Property ShipToNameField As String
        Public Property ShipToAddressField As String
        Public Property ShipToAddress2Field As String
        Public Property ShipToCityField As String
        Public Property ShipToStateField As String
        Public Property ShipToZipField As String
        Public Property OrderSummaryHeader As String
        Public Property SaveOrderForLaterMessage As String
        Public Property CouponCodeField As String
        Public Property ValidateButton As String
        Public Property CheckOutButton As String
        Public Property ItemTotalField As String
        Public Property ShippingField As String
        Public Property SalesTaxField As String
        Public Property OrderTotalField As String
        Public Property DiscountField As String
        Public Property QuantityField As String
        Public Property SpecialInstructionField As String
        Public Property SelectItemButton As String
        Public Property AddToOrderButton As String
        Public Property ShippingRegionLabel As String
        Public Property ShippingModeLabel As String
        Public Property ShippingFreeOverLabel As String
        Public Property BuyNowButton As String
        Public Property LoginOrGuestMessage As String
        Public Property PasswordEmail As String
        Public Property Password As String
        Public Property GuestButton As String
        Public Property PaymentInformationDescription As String
        Public Property CreateAnAccountMessage As String
        Public Property NameOrderField As String
        Public Property SaveForReorderMessage As String
        Public Property OkButton As String
        Public Property SaveButton As String
        Public Property NoButton As String
        Public Property SaveOrderHeader As String
        Public Property LoginOrGuestHeader As String
        Public Property Locked As Boolean
    
    End Class

End Namespace
