'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LicenseTrack
    Public Property Id As Integer
    Public Property UserId As Integer
    Public Property CompanyName As String
    Public Property Contact As String
    Public Property Phone As String
    Public Property Email As String
    Public Property LicensesPurchased As Short
    Public Property LicensesUsed As Short
    Public Property OpenDate As Date
    Public Property LastActionDate As Date
    Public Property Active As Boolean
    Public Property Version As Nullable(Of Short)
    Public Property AnnualExpiration As Nullable(Of Date)
    Public Property PaidInFull As Boolean

End Class
