'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class MasterAccount
        Public Property LoginId As Integer
        Public Property MasterName As String
        Public Property StripeAccount As String
        Public Property ServiceLevel As Byte
    
    End Class

End Namespace
