'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class OrderDetailOLD
        Public Property OrderDetailId As Integer
        Public Property OrderId As Integer
        Public Property Quantity As Nullable(Of Decimal)
        Public Property CatalogItemId As Nullable(Of Integer)
        Public Property Description As String
        Public Property UnitPrice As Nullable(Of Decimal)
        Public Property Weight As Nullable(Of Decimal)
        Public Property CurrencyId As Nullable(Of Integer)
        Public Property Taxable As Boolean
        Public Property Sku As String
        Public Property DiscountSchedule As String
        Public Property DiscountPercent As Decimal
        Public Property Length As Decimal
        Public Property Width As Decimal
        Public Property Height As Decimal
        Public Property Packagetype As String
        Public Property Oversize As Short
        Public Property InsuredValue As Decimal
        Public Property Option1 As String
        Public Property Option2 As String
        Public Property Shipping As Nullable(Of Decimal)
        Public Property PackageIndividually As Nullable(Of Boolean)
        Public Property MailListId As Nullable(Of Integer)
        Public Property FullDescription As String
        Public Property Download As Boolean
        Public Property SpecialInstructions As String
        Public Property ForWho As String
    
    End Class

End Namespace
