'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrderHeader
    Public Property OrderId As Integer
    Public Property UserId As Integer
    Public Property OrderDate As Date
    Public Property CustomerId As Nullable(Of Integer)
    Public Property OrderTotal As Decimal
    Public Property SalesTax As Decimal
    Public Property SalesTaxCode As Nullable(Of Integer)
    Public Property ShippingCharge As Decimal
    Public Property TransactionId As String
    Public Property QbUpdated As Boolean
    Public Property IpAddress As String
    Public Property AuthorizationCode As String
    Public Property OrderName As String
    Public Property SaveOrder As Boolean
    Public Property EmailSent As Boolean
    Public Property Delivery As Boolean
    Public Property OrderTime As String
    Public Property Later As Boolean
    Public Property ShippingId As Nullable(Of Integer)
    Public Property SalesTaxAmt As Nullable(Of Decimal)
    Public Property OrderSite As String
    Public Property OrderPage As String
    Public Property DiscountCode As String
    Public Property CouponId As Nullable(Of Integer)
    Public Property DiscountAmount As Nullable(Of Decimal)
    Public Property PostAuthRequired As Boolean
    Public Property Status As Nullable(Of Byte)
    Public Property bTestOrder As Nullable(Of Boolean)
    Public Property CustNoID As Nullable(Of Integer)
    Public Property PlayOrderId As Nullable(Of Integer)
    Public Property OrderCurrency As String
    Public Property ShipUps As Nullable(Of Boolean)
    Public Property ShipFedex As Nullable(Of Boolean)
    Public Property ShipService As String
    Public Property ShipResidence As Nullable(Of Boolean)
    Public Property MultiShip As Nullable(Of Boolean)
    Public Property AdId As Nullable(Of Integer)
    Public Property MerchEmailSent As Nullable(Of Boolean)
    Public Property OrderNotificationSent As Nullable(Of Boolean)
    Public Property AuthorizeOnly As Nullable(Of Boolean)
    Public Property Last4 As String
    Public Property UpsellUrl As String
    Public Property FreeGoodie As Nullable(Of Boolean)
    Public Property URLContinue As String
    Public Property AffiliateId As Nullable(Of Decimal)
    Public Property OrderSource As String
    Public Property SavedForLater As Boolean
    Public Property SavedEmailAddress As String
    Public Property PayPalPayId As String
    Public Property PayPalPayerId As String
    Public Property PayPalAuthorizationId As String

    Public Overridable Property CaptureEmails As ICollection(Of CaptureEmail) = New HashSet(Of CaptureEmail)
    Public Overridable Property Customer As Customer
    Public Overridable Property OrderDetails As ICollection(Of OrderDetail) = New HashSet(Of OrderDetail)
    Public Overridable Property OurCustomer As OurCustomer

End Class
