'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrderSubOption
    Public Property OrderSubOptionId As Integer
    Public Property OrderOptionId As Integer
    Public Property SubOptionId As Integer
    Public Property Price As Decimal

    Public Overridable Property ItemSubOption As ItemSubOption
    Public Overridable Property OrderDetailOption As OrderDetailOption

End Class
