'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OurAffiliate
    Public Property LoginId As Integer
    Public Property Name As String
    Public Property Address As String
    Public Property Address2 As String
    Public Property City As String
    Public Property State As String
    Public Property Zip As String
    Public Property Phone As String
    Public Property PayPalEmail As String
    Public Property W9 As Boolean
    Public Property Social As String
    Public Property IsAffiliate As Boolean
    Public Property Percentage As Short
    Public Property Percentage2 As Short
    Public Property FromAffiliate As Nullable(Of Integer)
    Public Property Initials As String

    Public Overridable Property C_login As C_login

End Class
