'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OurCustPayment
    Public Property OurCustPaymentId As Integer
    Public Property UserId As Integer
    Public Property SubscriptionId As String
    Public Property SubscriptionDate As Date
    Public Property OurPlanId As String
    Public Property Period As String
    Public Property PlanId As String
    Public Property Amount As Decimal
    Public Property Active As Boolean

    Public Overridable Property OurCustomer As OurCustomer

End Class
