'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OurCustomer
    Public Property UserId As Integer
    Public Property CustomerName As String
    Public Property ContactId As Nullable(Of Integer)
    Public Property Address1 As String
    Public Property Address2 As String
    Public Property City As String
    Public Property State As String
    Public Property Zip As String
    Public Property Country As String
    Public Property BillingZip As String
    Public Property BillingCountry As String
    Public Property Active As Nullable(Of Boolean)
    Public Property Phone1 As String
    Public Property Phone2 As String
    Public Property SendText As Boolean
    Public Property Email As String
    Public Property PrinterEmail As String
    Public Property StripePublishableKey As String
    Public Property StripeSecretKey As String
    Public Property TestStripeSecretKey As String
    Public Property TestStripePublishableKey As String
    Public Property StripeAccount As String
    Public Property StripeAccessToken As String
    Public Property bTestMode As Boolean
    Public Property Initials As String
    Public Property FirstVisit As Boolean
    Public Property DirectFlag As Boolean
    Public Property SignupStep As Byte
    Public Property MailAPIkey As String
    Public Property ContactName As String
    Public Property FaceBookAppId As String
    Public Property FaceBookSecretKey As String
    Public Property TwitterConsumerKey As String
    Public Property TwitterSecretKey As String
    Public Property ServiceLevel As Byte
    Public Property OpenDate As Date
    Public Property Affiliate As Boolean
    Public Property Qbooks As Boolean
    Public Property Coupons As Boolean
    Public Property CustomerTracking As Boolean
    Public Property UpsDesktop As Boolean
    Public Property DigitalDownloads As Boolean
    Public Property Labels As Boolean
    Public Property OtherOption2 As Boolean
    Public Property OtherOption3 As Boolean
    Public Property testingId As Nullable(Of Integer)
    Public Property GiftCertificates As Nullable(Of Boolean)
    Public Property UspsDesktop As Nullable(Of Boolean)
    Public Property FedexDesktop As Nullable(Of Boolean)
    Public Property StampsDesktop As Nullable(Of Boolean)
    Public Property CSVdownload As Nullable(Of Boolean)
    Public Property SalesTracking As Nullable(Of Boolean)
    Public Property FromAdId As Nullable(Of Integer)
    Public Property FromAffiliateId As Nullable(Of Integer)
    Public Property AutoResponder As Byte
    Public Property Currency As String
    Public Property CurrencySymbol As String
    Public Property EmailUserId As Nullable(Of Integer)
    Public Property StripeCustomerId As String
    Public Property QbCustomerId As String
    Public Property QuickbooksAccessToken As String
    Public Property QuickbooksSecretToken As String
    Public Property QBRealmId As String
    Public Property QbSalesAccount As String
    Public Property QbSalesTax As String
    Public Property QbSalesDiscounts As String
    Public Property QbFreightIncome As String
    Public Property QbCash As String
    Public Property QbCostOfGoods As String
    Public Property QbUndepositiedFunds As String
    Public Property QbSalesId As Nullable(Of Integer)
    Public Property QbSalesTaxId As Nullable(Of Integer)
    Public Property QbDiscountsId As Nullable(Of Integer)
    Public Property QbFreightId As Nullable(Of Integer)
    Public Property QbCashId As Nullable(Of Integer)
    Public Property QbCostofGoodsId As Nullable(Of Integer)
    Public Property QbUndepositedFundsId As Nullable(Of Integer)
    Public Property Annual As Boolean
    Public Property APIkey As String
    Public Property CouponCodeId As Nullable(Of Integer)
    Public Property Logoold As String
    Public Property PayPalUserName As String
    Public Property PayPalPassword As String
    Public Property PaypalSignature As String
    Public Property SubDomain As String
    Public Property CouponCode As String
    Public Property Logo As String
    Public Property EmailVerified As Nullable(Of Boolean)
    Public Property VerificationCode As String
    Public Property GetResponseKey As String
    Public Property ShowHelp As Nullable(Of Boolean)

    Public Overridable Property C_login As ICollection(Of C_login) = New HashSet(Of C_login)
    Public Overridable Property AffiliatePrograms As ICollection(Of AffiliateProgram) = New HashSet(Of AffiliateProgram)
    Public Overridable Property BuildaLinks As ICollection(Of BuildaLink) = New HashSet(Of BuildaLink)
    Public Overridable Property CartSetup As CartSetup
    Public Overridable Property CatalogLevel1 As ICollection(Of CatalogLevel1) = New HashSet(Of CatalogLevel1)
    Public Overridable Property CatalogLevel2 As ICollection(Of CatalogLevel2) = New HashSet(Of CatalogLevel2)
    Public Overridable Property CatalogLevel3 As ICollection(Of CatalogLevel3) = New HashSet(Of CatalogLevel3)
    Public Overridable Property Contact As Contact
    Public Overridable Property Coupons1 As ICollection(Of Coupon) = New HashSet(Of Coupon)
    Public Overridable Property Customers As ICollection(Of Customer) = New HashSet(Of Customer)
    Public Overridable Property EzShips As ICollection(Of EzShip) = New HashSet(Of EzShip)
    Public Overridable Property ItemOptions As ICollection(Of ItemOption) = New HashSet(Of ItemOption)
    Public Overridable Property ItemOptionGroups As ICollection(Of ItemOptionGroup) = New HashSet(Of ItemOptionGroup)
    Public Overridable Property ItemSubOptions As ICollection(Of ItemSubOption) = New HashSet(Of ItemSubOption)
    Public Overridable Property ItemUpsells As ICollection(Of ItemUpsell) = New HashSet(Of ItemUpsell)
    Public Overridable Property OrderHeaders As ICollection(Of OrderHeader) = New HashSet(Of OrderHeader)
    Public Overridable Property OurCustPayments As ICollection(Of OurCustPayment) = New HashSet(Of OurCustPayment)
    Public Overridable Property QuantityDiscounts As ICollection(Of QuantityDiscount) = New HashSet(Of QuantityDiscount)
    Public Overridable Property SingleCoupons As ICollection(Of SingleCoupon) = New HashSet(Of SingleCoupon)
    Public Overridable Property TaxStates As ICollection(Of TaxState) = New HashSet(Of TaxState)
    Public Overridable Property C_login1 As ICollection(Of C_login) = New HashSet(Of C_login)
    Public Overridable Property C_login2 As ICollection(Of C_login) = New HashSet(Of C_login)

End Class
