'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PaypalPaymentHistory
    Public Property PaypalPaymentId As Integer
    Public Property UserId As Integer
    Public Property PaymentInfo As String
    Public Property CreatedDate As Date

End Class
