'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PaypalIntegration
    Public Property PaypalIntegrationId As Integer
    Public Property UserId As Integer
    Public Property ClientId As String
    Public Property ClientSecret As String
    Public Property Currency As String
    Public Property Environment As String
    Public Property Amount As Nullable(Of Decimal)
    Public Property Active As Boolean

End Class
