'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class qryActiveCoupon
        Public Property UserId As Integer
        Public Property Couponid As Integer
        Public Property CouponCode As String
        Public Property DiscountTypeId As Byte
        Public Property ExpirationDate As Date
    
    End Class

End Namespace
