'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class qryBasicCatalogMaint
        Public Property CatalogItemId As Integer
        Public Property UniqueId As String
        Public Property UserId As Integer
        Public Property CatalogLevel3Id As Nullable(Of Integer)
        Public Property Sequence As Short
        Public Property Name As String
        Public Property Description As String
        Public Property Price As Nullable(Of Decimal)
        Public Property Taxable As Boolean
        Public Property Active As Boolean
        Public Property ItemOptionGroupId As Nullable(Of Integer)
        Public Property ItemGroupId As Nullable(Of Integer)
        Public Property Sku As String
        Public Property DiscountSchedule As String
        Public Property ImageSequence As Nullable(Of Short)
        Public Property Weight As Integer
        Public Property ReceiptMessage As String
        Public Property DigitalProduct As Boolean
        Public Property DigitalFileName As String
        Public Property FeaturedItem As Boolean
        Public Property FavoriteItem As Boolean
        Public Property UniqueItem As Boolean
        Public Property EmailListName As String
        Public Property DeliveryCharge As Decimal
        Public Property Option1 As String
        Public Property Option2 As String
        Public Property LandingPixel As String
        Public Property PurchasePixel As String
        Public Property CatalogImageId As Nullable(Of Integer)
        Public Property ImageThumb As String
        Public Property ImageLink As String
        Public Property ServiceLevel As Byte
        Public Property BasicCatalogDone As Boolean
        Public Property PackageType As String
        Public Property PackageIndividually As Nullable(Of Boolean)
        Public Property Length As Integer
        Public Property Width As Integer
        Public Property Height As Integer
        Public Property Oversize As Byte
        Public Property InsuredValue As Decimal
        Public Property ShippingCost As Decimal
        Public Property MailListId As String
        Public Property DigitalDownloads As Boolean
        Public Property AutoResponder As Byte
        Public Property MailAPIkey As String
    
    End Class

End Namespace
