'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class qryCartSetup
        Public Property UserId As Integer
        Public Property CustomerName As String
        Public Property ServiceLevel As Byte
        Public Property Active As Nullable(Of Boolean)
        Public Property ThankYouPage As String
        Public Property ListBySequence As Boolean
        Public Property Metric As Boolean
        Public Property MultiLevelCatalog As Boolean
        Public Property ShippingAdditionalItem As Nullable(Of Decimal)
        Public Property ShippingFirstItem As Nullable(Of Decimal)
        Public Property ShippingFreeOver As Nullable(Of Decimal)
        Public Property UseEzShip As Boolean
        Public Property CartFormat As Byte
        Public Property ChatCode As String
        Public Property TaxStateId As Nullable(Of Integer)
        Public Property TaxCountry As String
        Public Property TaxState As String
        Public Property TaxPercentage As Nullable(Of Decimal)
        Public Property TaxPercentage2 As Nullable(Of Decimal)
        Public Property Logo As String
        Public Property TimeZone As Nullable(Of Short)
        Public Property Coupons As Boolean
        Public Property FacebookLink As String
        Public Property TwitterLink As String
        Public Property PinterestLink As String
        Public Property gPlusLink As String
        Public Property InstagramLink As String
        Public Property UseFeaturedItems As Boolean
        Public Property ShowFavouriteItem As Nullable(Of Boolean)
        Public Property UseShades As Boolean
        Public Property FacebookPageName As String
        Public Property MyLiveChatId As String
        Public Property bTestMode As Boolean
        Public Property RotateFeaturedItems As Nullable(Of Boolean)
        Public Property RotationTimeFrame As Nullable(Of Integer)
        Public Property TrustLogo As String
        Public Property SiteColors As String
        Public Property ColorPaletteId As Integer
        Public Property ColorPaletteName As String
        Public Property CatalogBackground As String
        Public Property CatalogFontColor As String
        Public Property CatalogBorder As String
        Public Property CatalogFontName As String
        Public Property CatalogFontSize As Nullable(Of Byte)
        Public Property CatalogHeaderColor As String
        Public Property CatalogHeaderFontColor As String
        Public Property ItemBackground As String
        Public Property ItemNameFontColor As String
        Public Property ItemNameFontSize As String
        Public Property CategoryBackground As String
        Public Property CategoryFontColor As String
        Public Property CategoryFontSize As Nullable(Of Byte)
        Public Property DepartmentBackground As String
        Public Property DepartmentFont As String
        Public Property DepartmentFontSize As Nullable(Of Byte)
        Public Property OrderSummaryBackground As String
        Public Property OrderSummaryFont As String
        Public Property OrderSummaryFontSize As Nullable(Of Byte)
        Public Property OrderSummaryBorder As String
        Public Property OrderSummaryHeaderBackground As String
        Public Property OrderSummaryHeaderFont As String
        Public Property OrderPopupBackground As String
        Public Property OrderPopupFont As String
        Public Property OrderPopupBorder As String
        Public Property OrderPopupNameColor As String
        Public Property LoginFont As String
        Public Property LoginBackground As String
        Public Property LoginBorder As String
        Public Property LoginFontSize As Nullable(Of Byte)
        Public Property LoginButtonsColor As String
        Public Property LoginButtonsFont As String
        Public Property LoginGuestButtonColor As String
        Public Property LoginGuestFont As String
        Public Property PaymentBackBorder As String
        Public Property PaymentBackButtonColor As String
        Public Property PaymentBackFont As String
        Public Property PaymentButtonsFont As String
        Public Property PaymentButtonsColor As String
        Public Property PaymentFontSize As Nullable(Of Byte)
        Public Property PaymentBorder As String
        Public Property PaymentFont As String
        Public Property PaymentBackground As String
        Public Property LoginGuestBorder As String
        Public Property SignupStep As Byte
        Public Property OpenDate As Date
        Public Property StripePublishableKey As String
        Public Property TestStripePublishableKey As String
    
    End Class

End Namespace
