'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class qryCatalogItemListWide_Level3
    Public Property UserId As Integer
    Public Property CategoryId As Nullable(Of Integer)
    Public Property CategoryName As String
    Public Property CategorySequence As Nullable(Of Short)
    Public Property CategoryImage As String
    Public Property CatalogItemId As Integer
    Public Property CatalogItemSequence As Short
    Public Property CatalogItemName As String
    Public Property CatalogItemDescription As String
    Public Property Price As Nullable(Of Decimal)
    Public Property Sku As String
    Public Property ImageThumb As String
    Public Property ImageLink As String
    Public Property Weight As Integer
    Public Property Taxable As Boolean
    Public Property DigitalProduct As Boolean
    Public Property ItemOptionGroupId As Nullable(Of Integer)
    Public Property ItemOptionGroupName As String
    Public Property ItemOptionId As Nullable(Of Integer)
    Public Property ItemOptionDescription As String
    Public Property ItemOptionPrice As Nullable(Of Decimal)
    Public Property APIkey As String
    Public Property ImageSequence As Short
    Public Property FeaturedItem As Boolean
    Public Property FavoriteItem As Boolean
    Public Property CartFormat As Byte

End Class
