'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class qryCompleteOrder
    Public Property OrderId As Integer
    Public Property UserId As Integer
    Public Property OrderTotal As Decimal
    Public Property SalesTax As Decimal
    Public Property ShippingCharge As Decimal
    Public Property ShippingId As Nullable(Of Integer)
    Public Property DiscountAmount As Nullable(Of Decimal)
    Public Property IpAddress As String
    Public Property FirstName As String
    Public Property LastName As String
    Public Property Phone As String
    Public Property eMailAddr As String
    Public Property CCnumber As String
    Public Property expdate As String
    Public Property TransactionId As String
    Public Property AuthorizationCode As String
    Public Property bTestMode As Boolean
    Public Property OurCustEmail As String
    Public Property OurCustName As String
    Public Property OurCustAddress As String
    Public Property OurCustAddress2 As String
    Public Property OurCustCity As String
    Public Property OurCustState As String
    Public Property OurCustZip As String
    Public Property OurCustCountry As String
    Public Property OurCustPhone As String
    Public Property StripeToken As String
    Public Property Delivery As Boolean
    Public Property OrderTime As String
    Public Property Later As Boolean
    Public Property Address1 As String
    Public Property Address2 As String
    Public Property City As String
    Public Property State As String
    Public Property Zip As String
    Public Property CustomerId As Nullable(Of Integer)
    Public Property AffiliateId As Nullable(Of Integer)
    Public Property Name As String
    Public Property StripeAccount As String
    Public Property OurCustSecretKey As String
    Public Property OurCustTestSecretKey As String
    Public Property Currency As String
    Public Property Country As String
    Public Property ShipToAddress1 As String
    Public Property ShipToAddress2 As String
    Public Property ShipToCity As String
    Public Property ShipToState As String
    Public Property ShipToZip As String
    Public Property ShipToCountry As String
    Public Property ShipToName As String
    Public Property CompanyName As String
    Public Property ReceiptMessage As String
    Public Property FacebookLink As String
    Public Property TwitterLink As String
    Public Property PinterestLink As String
    Public Property gPlusLink As String
    Public Property InstagramLink As String
    Public Property SignupStep As Byte
    Public Property MailAPIkey As String
    Public Property ServiceLevel As Byte
    Public Property AutoResponder As Byte
    Public Property AutoResponderToken As String
    Public Property EmailListId As String
    Public Property StripeAccessToken As String

End Class
