'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class qryCatalogItemByAPIkey
        Public Property ItemId As Integer
        Public Property Name As String
        Public Property UserId As Integer
        Public Property APIKey As String
    
    End Class

End Namespace
