'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class qryCatalogItemList_Level1
    Public Property UserId As Integer
    Public Property CategoryLevel1Name As String
    Public Property CategoryLevel1Sequence As Byte
    Public Property DepartmentId As Integer
    Public Property CategoryLevel2Sequence As Byte
    Public Property CategoryLevel2Name As String
    Public Property CategoryId As Integer
    Public Property CategorySequence As Short
    Public Property CategoryName As String
    Public Property CategoryImage As String
    Public Property CatalogItemId As Integer
    Public Property CatalogItemSequence As Short
    Public Property CatalogItemName As String
    Public Property CatalogItemDescription As String
    Public Property Price As Decimal
    Public Property Active As Boolean
    Public Property Sku As String
    Public Property ImageThumb As String

End Class
