'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class qryCompleteOrderWithDetail
        Public Property OrderId As Integer
        Public Property UserId As Integer
        Public Property OrderDate As Date
        Public Property FirstName As String
        Public Property LastName As String
        Public Property OrderTotal As Decimal
        Public Property SalesTax As Decimal
        Public Property ShippingCharge As Decimal
        Public Property SalesTaxAmt As Nullable(Of Decimal)
        Public Property DiscountAmount As Nullable(Of Decimal)
        Public Property OrderDetailId As Integer
        Public Property Quantity As Decimal
        Public Property Name As String
        Public Property Price As Nullable(Of Decimal)
        Public Property Description As String
        Public Property OptionPrice As Nullable(Of Decimal)
    
    End Class

End Namespace
