'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class qryForSaveThisOrder
    Public Property OrderId As Integer
    Public Property UserId As Integer
    Public Property OrderTotal As Decimal
    Public Property SalesTax As Decimal
    Public Property ShippingCharge As Decimal
    Public Property IpAddress As String
    Public Property TransactionId As String
    Public Property AuthorizationCode As String
    Public Property bTestMode As Boolean
    Public Property OurCustEmail As String
    Public Property OurCustName As String
    Public Property OurCustAddress As String
    Public Property OurCustAddress2 As String
    Public Property OurCustCity As String
    Public Property OurCustState As String
    Public Property OurCustZip As String
    Public Property OurCustCountry As String
    Public Property OurCustPhone As String
    Public Property Delivery As Boolean
    Public Property OrderTime As String
    Public Property Later As Boolean
    Public Property AffiliateId As Nullable(Of Integer)
    Public Property Name As String
    Public Property StripeAccount As String
    Public Property Currency As String
    Public Property ReceiptMessage As String
    Public Property FacebookLink As String
    Public Property TwitterLink As String
    Public Property PinterestLink As String
    Public Property gPlusLink As String
    Public Property InstagramLink As String
    Public Property SavedEmailAddress As String
    Public Property SavedForLater As Boolean

End Class
