'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class qryOrderDetailOptionTotal
        Public Property OrderDetailId As Integer
        Public Property OptionPrice As Nullable(Of Decimal)
    
    End Class

End Namespace
