'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class qryOrderTotal
        Public Property OrderId As Integer
        Public Property itemtotal As Nullable(Of Decimal)
        Public Property OptionTotal As Nullable(Of Decimal)
        Public Property SalesTax As Decimal
        Public Property ShippingCharge As Decimal
        Public Property DiscountAmount As Nullable(Of Decimal)
        Public Property OptionPrice As Nullable(Of Decimal)
        Public Property Currency As String
    
    End Class

End Namespace
