'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class qryTaxStatew_Name
    Public Property TaxStateId As Integer
    Public Property TaxState As String
    Public Property Name As String
    Public Property UserId As Integer
    Public Property TaxPercentage As Nullable(Of Decimal)
    Public Property TaxCountry As String
    Public Property TaxPercentage2 As Decimal
    Public Property QbTaxCodeId As Nullable(Of Integer)

End Class
