'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class QuantityDiscount
    Public Property QuantityDiscountId As Integer
    Public Property UserId As Integer
    Public Property DiscSchedule As String
    Public Property Quantity As Integer
    Public Property discount As Decimal
    Public Property Percent As Boolean

    Public Overridable Property OurCustomer As OurCustomer

End Class
