'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class QuickBookCustomer
    Public Property QuickBookCustomerId As Integer
    Public Property UserId As Integer
    Public Property ConsumerKey As String
    Public Property ConsumerSecret As String
    Public Property Active As Boolean
    Public Property QBCustomerApiId As String

    Public Overridable Property QuickBookCustomer1 As QuickBookCustomer
    Public Overridable Property QuickBookCustomer2 As QuickBookCustomer

End Class
