'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class SecurityObject
        Public Property ObjectId As Integer
        Public Property Name As String
    
        Public Overridable Property UserSecurities As ICollection(Of UserSecurity) = New HashSet(Of UserSecurity)
    
    End Class

End Namespace
