'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class SingleCoupon
        Public Property SingleCouponId As Integer
        Public Property UserId As Integer
        Public Property Amount As Nullable(Of Decimal)
        Public Property ExpirationDate As Nullable(Of Date)
        Public Property Used As Boolean
    
        Public Overridable Property OurCustomer As OurCustomer
    
    End Class

End Namespace
