'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SplitTestCapture
    Public Property SplitTestCaptureId As Integer
    Public Property IP As String
    Public Property SplitTestLinkId As Integer
    Public Property Time As Date

    Public Overridable Property SplitTestLink As SplitTestLink

End Class
