'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SplitTest
    Public Property SplitTestID As Integer
    Public Property TestName As String
    Public Property SendToSamePage As Boolean

    Public Overridable Property SplitTestLinks As ICollection(Of SplitTestLink) = New HashSet(Of SplitTestLink)

End Class
