'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class TaxState
        Public Property TaxStateId As Integer
        Public Property UserId As Integer
        Public Property TaxCountry As String
        Public Property TaxState1 As String
        Public Property TaxOnShip As Boolean
        Public Property TaxPercentage As Nullable(Of Decimal)
        Public Property TaxPercentage2 As Decimal
        Public Property QbTaxCodeId As Nullable(Of Integer)
    
        Public Overridable Property OurCustomer As OurCustomer
    
    End Class

End Namespace
