'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class UpsSignup
        Public Property UpsSignupId As Integer
        Public Property UserId As Integer
        Public Property UpsUserId As String
        Public Property Title As String
        Public Property Name As String
        Public Property Company As String
        Public Property Address1 As String
        Public Property Address2 As String
        Public Property Address3 As String
        Public Property City As String
        Public Property State As String
        Public Property Zip As String
        Public Property Country As String
        Public Property Phone As String
        Public Property Extension As String
        Public Property Email As String
        Public Property ShipperNumber As String
        Public Property PickupZipCode As String
        Public Property PickupCountry As String
        Public Property SalesRep As Nullable(Of Boolean)
        Public Property URL As String
    
    End Class

End Namespace
