'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class UserSecurity
        Public Property UserSecurityId As Integer
        Public Property ObjectId As Integer
        Public Property LoginId As Integer
        Public Property UserId As Integer
    
        Public Overridable Property SecurityObject As SecurityObject
    
    End Class

End Namespace
