'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace OnlineSales.Web

    Partial Public Class USPSShipping
        Public Property Id As Integer
        Public Property UserId As String
        Public Property Url As String
        Public Property Username As String
        Public Property Password As String
        Public Property AdditionalHandlingCharge As String
        Public Property CarrierServicesOfferedDomestic As String
        Public Property CarrierServicesOfferedInternational As String
    
    End Class

End Namespace
