'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VisitorAction
    Public Property VisitorActionsId As Short
    Public Property ActionDescriptions As String

    Public Overridable Property VisitorTrackings As ICollection(Of VisitorTracking) = New HashSet(Of VisitorTracking)

End Class
